const countries = [
    { "Name": "Afghanistan", "Code": "AF", "IDD": "+93" },
    { "Name": "Åland Islands", "Code": "AX", "IDD": "+358-18" },
    { "Name": "Albania", "Code": "AL", "IDD": "+355" },
    { "Name": "Algeria", "Code": "DZ", "IDD": "+213" },
    { "Name": "American Samoa", "Code": "AS", "IDD": "+1-684" },
    { "Name": "Andorra", "Code": "AD", "IDD": "+376" },
    { "Name": "Angola", "Code": "AO", "IDD": "+244" },
    { "Name": "Anguilla", "Code": "AI", "IDD": "+1-264" },
    { "Name": "Antarctica", "Code": "AQ", "IDD": "+" },
    { "Name": "Antigua and Barbuda", "Code": "AG", "IDD": "+1-268" },
    { "Name": "Argentina", "Code": "AR", "IDD": "+54" },
    { "Name": "Armenia", "Code": "AM", "IDD": "+374" },
    { "Name": "Aruba", "Code": "AW", "IDD": "+297" },
    { "Name": "Australia", "Code": "AU", "IDD": "+61" },
    { "Name": "Austria", "Code": "AT", "IDD": "+43" },
    { "Name": "Azerbaijan", "Code": "AZ", "IDD": "+994" },
    { "Name": "Bahamas, The", "Code": "BS", "IDD": "+1-242" },
    { "Name": "Bahrain", "Code": "BH", "IDD": "+973" },
    { "Name": "Bangladesh", "Code": "BD", "IDD": "+880" },
    { "Name": "Barbados", "Code": "BB", "IDD": "+1-246" },
    { "Name": "Belarus", "Code": "BY", "IDD": "+375" },
    { "Name": "Belgium", "Code": "BE", "IDD": "+32" },
    { "Name": "Belize", "Code": "BZ", "IDD": "+501" },
    { "Name": "Benin", "Code": "BJ", "IDD": "+229" },
    { "Name": "Bermuda", "Code": "BM", "IDD": "+1-441" },
    { "Name": "Bhutan", "Code": "BT", "IDD": "+975" },
    { "Name": "Bolivarian Republic of Venezuela", "Code": "VE", "IDD": "+58" },
    { "Name": "Bolivia", "Code": "BO", "IDD": "+591" },
    { "Name": "Bonaire, Sint Eustatius and Saba", "Code": "BQ", "IDD": "+599" },
    { "Name": "Bosnia and Herzegovina", "Code": "BA", "IDD": "+387" },
    { "Name": "Botswana", "Code": "BW", "IDD": "+267" },
    { "Name": "Bouvet Island", "Code": "BV", "IDD": "+" },
    { "Name": "Brazil", "Code": "BR", "IDD": "+55" },
    { "Name": "British Indian Ocean Territory", "Code": "IO", "IDD": "+246" },
    { "Name": "Brunei", "Code": "BN", "IDD": "+673" },
    { "Name": "Bulgaria", "Code": "BG", "IDD": "+359" },
    { "Name": "Burkina Faso", "Code": "BF", "IDD": "+226" },
    { "Name": "Burundi", "Code": "BI", "IDD": "+257" },
    { "Name": "Cabo Verde", "Code": "CV", "IDD": "+238" },
    { "Name": "Cambodia", "Code": "KH", "IDD": "+855" },
    { "Name": "Cameroon", "Code": "CM", "IDD": "+237" },
    { "Name": "Canada", "Code": "CA", "IDD": "+1" },
    { "Name": "Cayman Islands", "Code": "KY", "IDD": "+1-345" },
    { "Name": "Central African Republic", "Code": "CF", "IDD": "+236" },
    { "Name": "Chad", "Code": "TD", "IDD": "+235" },
    { "Name": "Chile", "Code": "CL", "IDD": "+56" },
    { "Name": "China", "Code": "CN", "IDD": "+86" },
    { "Name": "Christmas Island", "Code": "CX", "IDD": "+61" },
    { "Name": "Cocos (Keeling) Islands", "Code": "CC", "IDD": "+61" },
    { "Name": "Colombia", "Code": "CO", "IDD": "+57" },
    { "Name": "Comoros", "Code": "KM", "IDD": "+269" },
    { "Name": "Congo", "Code": "CG", "IDD": "+242" },
    { "Name": "Congo (DRC)", "Code": "CD", "IDD": "+243" },
    { "Name": "Cook Islands", "Code": "CK", "IDD": "+682" },
    { "Name": "Costa Rica", "Code": "CR", "IDD": "+506" },
    { "Name": "Côte d'Ivoire", "Code": "CI", "IDD": "+225" },
    { "Name": "Croatia", "Code": "HR", "IDD": "+385" },
    { "Name": "Cuba", "Code": "CU", "IDD": "+53" },
    { "Name": "Curaçao", "Code": "CW", "IDD": "+599" },
    { "Name": "Cyprus", "Code": "CY", "IDD": "+357" },
    { "Name": "Czech Republic", "Code": "CZ", "IDD": "+420" },
    { "Name": "Democratic Republic of Timor-Leste", "Code": "TL", "IDD": "+670" },
    { "Name": "Denmark", "Code": "DK", "IDD": "+45" },
    { "Name": "Djibouti", "Code": "DJ", "IDD": "+253" },
    { "Name": "Dominica", "Code": "DM", "IDD": "+1-767" },
    { "Name": "Dominican Republic", "Code": "DO", "IDD": "+1-809 and 1-829" },
    { "Name": "Ecuador", "Code": "EC", "IDD": "+593" },
    { "Name": "Egypt", "Code": "EG", "IDD": "+20" },
    { "Name": "El Salvador", "Code": "SV", "IDD": "+503" },
    { "Name": "Equatorial Guinea", "Code": "GQ", "IDD": "+240" },
    { "Name": "Eritrea", "Code": "ER", "IDD": "+291" },
    { "Name": "Estonia", "Code": "EE", "IDD": "+372" },
    { "Name": "Ethiopia", "Code": "ET", "IDD": "+251" },
    { "Name": "Falkland Islands (Islas Malvinas)", "Code": "FK", "IDD": "+500" },
    { "Name": "Faroe Islands", "Code": "FO", "IDD": "+298" },
    { "Name": "Fiji Islands", "Code": "FJ", "IDD": "+679" },
    { "Name": "Finland", "Code": "FI", "IDD": "+358" },
    { "Name": "France", "Code": "FR", "IDD": "+33" },
    { "Name": "French Guiana", "Code": "GF", "IDD": "+594" },
    { "Name": "French Polynesia", "Code": "PF", "IDD": "+689" },
    { "Name": "French Southern and Antarctic Lands", "Code": "TF", "IDD": "+" },
    { "Name": "Gabon", "Code": "GA", "IDD": "+241" },
    { "Name": "Gambia, The", "Code": "GM", "IDD": "+220" },
    { "Name": "Georgia", "Code": "GE", "IDD": "+995" },
    { "Name": "Germany", "Code": "DE", "IDD": "+49" },
    { "Name": "Ghana", "Code": "GH", "IDD": "+233" },
    { "Name": "Gibraltar", "Code": "GI", "IDD": "+350" },
    { "Name": "Greece", "Code": "GR", "IDD": "+30" },
    { "Name": "Greenland", "Code": "GL", "IDD": "+299" },
    { "Name": "Grenada", "Code": "GD", "IDD": "+1-473" },
    { "Name": "Guadeloupe", "Code": "GP", "IDD": "+590" },
    { "Name": "Guam", "Code": "GU", "IDD": "+1-671" },
    { "Name": "Guatemala", "Code": "GT", "IDD": "+502" },
    { "Name": "Guernsey", "Code": "GG", "IDD": "+44-1481" },
    { "Name": "Guinea", "Code": "GN", "IDD": "+224" },
    { "Name": "Guinea-Bissau", "Code": "GW", "IDD": "+245" },
    { "Name": "Guyana", "Code": "GY", "IDD": "+592" },
    { "Name": "Haiti", "Code": "HT", "IDD": "+509" },
    { "Name": "Heard Island and McDonald Islands", "Code": "HM", "IDD": "+ " },
    { "Name": "Honduras", "Code": "HN", "IDD": "+504" },
    { "Name": "Hong Kong SAR", "Code": "HK", "IDD": "+852" },
    { "Name": "Hungary", "Code": "HU", "IDD": "+36" },
    { "Name": "Iceland", "Code": "IS", "IDD": "+354" },
    { "Name": "India", "Code": "IN", "IDD": "+91" },
    { "Name": "Indonesia", "Code": "ID", "IDD": "+62" },
    { "Name": "Iran", "Code": "IR", "IDD": "+98" },
    { "Name": "Iraq", "Code": "IQ", "IDD": "+964" },
    { "Name": "Ireland", "Code": "IE", "IDD": "+353" },
    { "Name": "Israel", "Code": "IL", "IDD": "+972" },
    { "Name": "Italy", "Code": "IT", "IDD": "+39" },
    { "Name": "Jamaica", "Code": "JM", "IDD": "+1-876" },
    { "Name": "Jan Mayen", "Code": "SJ", "IDD": "+47" },
    { "Name": "Japan", "Code": "JP", "IDD": "+81" },
    { "Name": "Jersey", "Code": "JE", "IDD": "+44-1534" },
    { "Name": "Jordan", "Code": "JO", "IDD": "+962" },
    { "Name": "Kazakhstan", "Code": "KZ", "IDD": "+7" },
    { "Name": "Kenya", "Code": "KE", "IDD": "+254" },
    { "Name": "Kiribati", "Code": "KI", "IDD": "+686" },
    { "Name": "Korea", "Code": "KR", "IDD": "+82" },
    { "Name": "Kosovo", "Code": "XK", "IDD": "+" },
    { "Name": "Kuwait", "Code": "KW", "IDD": "+965" },
    { "Name": "Kyrgyzstan", "Code": "KG", "IDD": "+996" },
    { "Name": "Laos", "Code": "LA", "IDD": "+856" },
    { "Name": "Latvia", "Code": "LV", "IDD": "+371" },
    { "Name": "Lebanon", "Code": "LB", "IDD": "+961" },
    { "Name": "Lesotho", "Code": "LS", "IDD": "+266" },
    { "Name": "Liberia", "Code": "LR", "IDD": "+231" },
    { "Name": "Libya", "Code": "LY", "IDD": "+218" },
    { "Name": "Liechtenstein", "Code": "LI", "IDD": "+423" },
    { "Name": "Lithuania", "Code": "LT", "IDD": "+370" },
    { "Name": "Luxembourg", "Code": "LU", "IDD": "+352" },
    { "Name": "Macao SAR", "Code": "MO", "IDD": "+853" },
    { "Name": "Macedonia, Former Yugoslav Republic of", "Code": "MK", "IDD": "+389" },
    { "Name": "Madagascar", "Code": "MG", "IDD": "+261" },
    { "Name": "Malawi", "Code": "MW", "IDD": "+265" },
    { "Name": "Malaysia", "Code": "MY", "IDD": "+60" },
    { "Name": "Maldives", "Code": "MV", "IDD": "+960" },
    { "Name": "Mali", "Code": "ML", "IDD": "+223" },
    { "Name": "Malta", "Code": "MT", "IDD": "+356" },
    { "Name": "Man, Isle of", "Code": "IM", "IDD": "+44-1624" },
    { "Name": "Marshall Islands", "Code": "MH", "IDD": "+692" },
    { "Name": "Martinique", "Code": "MQ", "IDD": "+596" },
    { "Name": "Mauritania", "Code": "MR", "IDD": "+222" },
    { "Name": "Mauritius", "Code": "MU", "IDD": "+230" },
    { "Name": "Mayotte", "Code": "YT", "IDD": "+262" },
    { "Name": "Mexico", "Code": "MX", "IDD": "+52" },
    { "Name": "Micronesia", "Code": "FM", "IDD": "+691" },
    { "Name": "Moldova", "Code": "MD", "IDD": "+373" },
    { "Name": "Monaco", "Code": "MC", "IDD": "+377" },
    { "Name": "Mongolia", "Code": "MN", "IDD": "+976" },
    { "Name": "Montenegro", "Code": "ME", "IDD": "+382" },
    { "Name": "Montserrat", "Code": "MS", "IDD": "+1-664" },
    { "Name": "Morocco", "Code": "MA", "IDD": "+212" },
    { "Name": "Mozambique", "Code": "MZ", "IDD": "+258" },
    { "Name": "Myanmar", "Code": "MM", "IDD": "+95" },
    { "Name": "Namibia", "Code": "NA", "IDD": "+264" },
    { "Name": "Nauru", "Code": "NR", "IDD": "+674" },
    { "Name": "Nepal", "Code": "NP", "IDD": "+977" },
    { "Name": "Netherlands", "Code": "NL", "IDD": "+31" },
    { "Name": "New Caledonia", "Code": "NC", "IDD": "+687" },
    { "Name": "New Zealand", "Code": "NZ", "IDD": "+64" },
    { "Name": "Nicaragua", "Code": "NI", "IDD": "+505" },
    { "Name": "Niger", "Code": "NE", "IDD": "+227" },
    { "Name": "Nigeria", "Code": "NG", "IDD": "+234" },
    { "Name": "Niue", "Code": "NU", "IDD": "+683" },
    { "Name": "Norfolk Island", "Code": "NF", "IDD": "+672" },
    { "Name": "North Korea", "Code": "KP", "IDD": "+850" },
    { "Name": "Northern Mariana Islands", "Code": "MP", "IDD": "+1-670" },
    { "Name": "Norway", "Code": "NO", "IDD": "+47" },
    { "Name": "Oman", "Code": "OM", "IDD": "+968" },
    { "Name": "Pakistan", "Code": "PK", "IDD": "+92" },
    { "Name": "Palau", "Code": "PW", "IDD": "+680" },
    { "Name": "Palestinian Authority", "Code": "PS", "IDD": "+970" },
    { "Name": "Panama", "Code": "PA", "IDD": "+507" },
    { "Name": "Papua New Guinea", "Code": "PG", "IDD": "+675" },
    { "Name": "Paraguay", "Code": "PY", "IDD": "+595" },
    { "Name": "Peru", "Code": "PE", "IDD": "+51" },
    { "Name": "Philippines", "Code": "PH", "IDD": "+63" },
    { "Name": "Pitcairn Islands", "Code": "PN", "IDD": "+870" },
    { "Name": "Poland", "Code": "PL", "IDD": "+48" },
    { "Name": "Portugal", "Code": "PT", "IDD": "+351" },
    { "Name": "Puerto Rico", "Code": "PR", "IDD": "+1-787 and 1-939" },
    { "Name": "Qatar", "Code": "QA", "IDD": "+974" },
    { "Name": "Reunion", "Code": "RE", "IDD": "+262" },
    { "Name": "Romania", "Code": "RO", "IDD": "+40" },
    { "Name": "Russia", "Code": "RU", "IDD": "+7" },
    { "Name": "Rwanda", "Code": "RW", "IDD": "+250" },
    { "Name": "Saint Barthélemy", "Code": "BL", "IDD": "+590" },
    { "Name": "Saint Helena, Ascension and Tristan da Cunha", "Code": "SH", "IDD": "+290" },
    { "Name": "Saint Kitts and Nevis", "Code": "KN", "IDD": "+1-869" },
    { "Name": "Saint Lucia", "Code": "LC", "IDD": "+1-758" },
    { "Name": "Saint Martin (French part)", "Code": "MF", "IDD": "+590" },
    { "Name": "Saint Pierre and Miquelon", "Code": "PM", "IDD": "+508" },
    { "Name": "Saint Vincent and the Grenadines", "Code": "VC", "IDD": "+1-784" },
    { "Name": "Samoa", "Code": "WS", "IDD": "+685" },
    { "Name": "San Marino", "Code": "SM", "IDD": "+378" },
    { "Name": "São Tomé and Príncipe", "Code": "ST", "IDD": "+239" },
    { "Name": "Saudi Arabia", "Code": "SA", "IDD": "+966" },
    { "Name": "Senegal", "Code": "SN", "IDD": "+221" },
    { "Name": "Serbia", "Code": "RS", "IDD": "+381" },
    { "Name": "Seychelles", "Code": "SC", "IDD": "+248" },
    { "Name": "Sierra Leone", "Code": "SL", "IDD": "+232" },
    { "Name": "Singapore", "Code": "SG", "IDD": "+65" },
    { "Name": "Sint Maarten (Dutch part)", "Code": "SX", "IDD": "+599" },
    { "Name": "Slovakia", "Code": "SK", "IDD": "+421" },
    { "Name": "Slovenia", "Code": "SI", "IDD": "+386" },
    { "Name": "Solomon Islands", "Code": "SB", "IDD": "+677" },
    { "Name": "Somalia", "Code": "SO", "IDD": "+252" },
    { "Name": "South Africa", "Code": "ZA", "IDD": "+27" },
    { "Name": "South Georgia and the South Sandwich Islands", "Code": "GS", "IDD": "+" },
    { "Name": "South Sudan", "Code": "SS", "IDD": "+211" },
    { "Name": "Spain", "Code": "ES", "IDD": "+34" },
    { "Name": "Sri Lanka", "Code": "LK", "IDD": "+94" },
    { "Name": "Sudan", "Code": "SD", "IDD": "+249" },
    { "Name": "Suriname", "Code": "SR", "IDD": "+597" },
    { "Name": "Svalbard", "Code": "SJ", "IDD": "+47" },
    { "Name": "Swaziland", "Code": "SZ", "IDD": "+268" },
    { "Name": "Sweden", "Code": "SE", "IDD": "+46" },
    { "Name": "Switzerland", "Code": "CH", "IDD": "+41" },
    { "Name": "Syria", "Code": "SY", "IDD": "+963" },
    { "Name": "Taiwan", "Code": "TW", "IDD": "+886" },
    { "Name": "Tajikistan", "Code": "TJ", "IDD": "+992" },
    { "Name": "Tanzania", "Code": "TZ", "IDD": "+255" },
    { "Name": "Thailand", "Code": "TH", "IDD": "+66" },
    { "Name": "Togo", "Code": "TG", "IDD": "+228" },
    { "Name": "Tokelau", "Code": "TK", "IDD": "+690" },
    { "Name": "Tonga", "Code": "TO", "IDD": "+676" },
    { "Name": "Trinidad and Tobago", "Code": "TT", "IDD": "+1-868" },
    { "Name": "Tunisia", "Code": "TN", "IDD": "+216" },
    { "Name": "Turkey", "Code": "TR", "IDD": "+90" },
    { "Name": "Turkmenistan", "Code": "TM", "IDD": "+993" },
    { "Name": "Turks and Caicos Islands", "Code": "TC", "IDD": "+1-649" },
    { "Name": "Tuvalu", "Code": "TV", "IDD": "+688" },
    { "Name": "U.S. Minor Outlying Islands", "Code": "UM", "IDD": "+1" },
    { "Name": "Uganda", "Code": "UG", "IDD": "+256" },
    { "Name": "Ukraine", "Code": "UA", "IDD": "+380" },
    { "Name": "United Arab Emirates", "Code": "AE", "IDD": "+971" },
    { "Name": "United Kingdom", "Code": "GB", "IDD": "+44" },
    { "Name": "United States", "Code": "US", "IDD": "+1" },
    { "Name": "Uruguay", "Code": "UY", "IDD": "+598" },
    { "Name": "Uzbekistan", "Code": "UZ", "IDD": "+998" },
    { "Name": "Vanuatu", "Code": "VU", "IDD": "+678" },
    { "Name": "Vatican City", "Code": "VA", "IDD": "+379" },
    { "Name": "Vietnam", "Code": "VN", "IDD": "+84" },
    { "Name": "Virgin Islands, U.S.", "Code": "VI", "IDD": "+1-340" },
    { "Name": "Virgin Islands, British", "Code": "VG", "IDD": "+1-284" },
    { "Name": "Wallis and Futuna", "Code": "WF", "IDD": "+681" },
    { "Name": "Yemen", "Code": "YE", "IDD": "+967" },
    { "Name": "Zambia", "Code": "ZM", "IDD": "+260" },
    { "Name": "Zimbabwe", "Code": "ZW", "IDD": "+263" }
]