const countries = [
    { "Name": "Afghanistan", "Alpha-2": "AF", "IDD": "+93" },
    { "Name": "Åland Islands", "Alpha-2": "AX", "IDD": "+358-18" },
    { "Name": "Albania", "Alpha-2": "AL", "IDD": "+355" },
    { "Name": "Algeria", "Alpha-2": "DZ", "IDD": "+213" },
    { "Name": "American Samoa", "Alpha-2": "AS", "IDD": "+1-684" },
    { "Name": "Andorra", "Alpha-2": "AD", "IDD": "+376" },
    { "Name": "Angola", "Alpha-2": "AO", "IDD": "+244" },
    { "Name": "Anguilla", "Alpha-2": "AI", "IDD": "+1-264" },
    { "Name": "Antarctica", "Alpha-2": "AQ", "IDD": "+" },
    { "Name": "Antigua and Barbuda", "Alpha-2": "AG", "IDD": "+1-268" },
    { "Name": "Argentina", "Alpha-2": "AR", "IDD": "+54" },
    { "Name": "Armenia", "Alpha-2": "AM", "IDD": "+374" },
    { "Name": "Aruba", "Alpha-2": "AW", "IDD": "+297" },
    { "Name": "Australia", "Alpha-2": "AU", "IDD": "+61" },
    { "Name": "Austria", "Alpha-2": "AT", "IDD": "+43" },
    { "Name": "Azerbaijan", "Alpha-2": "AZ", "IDD": "+994" },
    { "Name": "Bahamas, The", "Alpha-2": "BS", "IDD": "+1-242" },
    { "Name": "Bahrain", "Alpha-2": "BH", "IDD": "+973" },
    { "Name": "Bangladesh", "Alpha-2": "BD", "IDD": "+880" },
    { "Name": "Barbados", "Alpha-2": "BB", "IDD": "+1-246" },
    { "Name": "Belarus", "Alpha-2": "BY", "IDD": "+375" },
    { "Name": "Belgium", "Alpha-2": "BE", "IDD": "+32" },
    { "Name": "Belize", "Alpha-2": "BZ", "IDD": "+501" },
    { "Name": "Benin", "Alpha-2": "BJ", "IDD": "+229" },
    { "Name": "Bermuda", "Alpha-2": "BM", "IDD": "+1-441" },
    { "Name": "Bhutan", "Alpha-2": "BT", "IDD": "+975" },
    { "Name": "Bolivarian Republic of Venezuela", "Alpha-2": "VE", "IDD": "+58" },
    { "Name": "Bolivia", "Alpha-2": "BO", "IDD": "+591" },
    { "Name": "Bonaire, Sint Eustatius and Saba", "Alpha-2": "BQ", "IDD": "+599" },
    { "Name": "Bosnia and Herzegovina", "Alpha-2": "BA", "IDD": "+387" },
    { "Name": "Botswana", "Alpha-2": "BW", "IDD": "+267" },
    { "Name": "Bouvet Island", "Alpha-2": "BV", "IDD": "+" },
    { "Name": "Brazil", "Alpha-2": "BR", "IDD": "+55" },
    { "Name": "British Indian Ocean Territory", "Alpha-2": "IO", "IDD": "+246" },
    { "Name": "Brunei", "Alpha-2": "BN", "IDD": "+673" },
    { "Name": "Bulgaria", "Alpha-2": "BG", "IDD": "+359" },
    { "Name": "Burkina Faso", "Alpha-2": "BF", "IDD": "+226" },
    { "Name": "Burundi", "Alpha-2": "BI", "IDD": "+257" },
    { "Name": "Cabo Verde", "Alpha-2": "CV", "IDD": "+238" },
    { "Name": "Cambodia", "Alpha-2": "KH", "IDD": "+855" },
    { "Name": "Cameroon", "Alpha-2": "CM", "IDD": "+237" },
    { "Name": "Canada", "Alpha-2": "CA", "IDD": "+1" },
    { "Name": "Cayman Islands", "Alpha-2": "KY", "IDD": "+1-345" },
    { "Name": "Central African Republic", "Alpha-2": "CF", "IDD": "+236" },
    { "Name": "Chad", "Alpha-2": "TD", "IDD": "+235" },
    { "Name": "Chile", "Alpha-2": "CL", "IDD": "+56" },
    { "Name": "China", "Alpha-2": "CN", "IDD": "+86" },
    { "Name": "Christmas Island", "Alpha-2": "CX", "IDD": "+61" },
    { "Name": "Cocos (Keeling) Islands", "Alpha-2": "CC", "IDD": "+61" },
    { "Name": "Colombia", "Alpha-2": "CO", "IDD": "+57" },
    { "Name": "Comoros", "Alpha-2": "KM", "IDD": "+269" },
    { "Name": "Congo", "Alpha-2": "CG", "IDD": "+242" },
    { "Name": "Congo (DRC)", "Alpha-2": "CD", "IDD": "+243" },
    { "Name": "Cook Islands", "Alpha-2": "CK", "IDD": "+682" },
    { "Name": "Costa Rica", "Alpha-2": "CR", "IDD": "+506" },
    { "Name": "Côte d'Ivoire", "Alpha-2": "CI", "IDD": "+225" },
    { "Name": "Croatia", "Alpha-2": "HR", "IDD": "+385" },
    { "Name": "Cuba", "Alpha-2": "CU", "IDD": "+53" },
    { "Name": "Curaçao", "Alpha-2": "CW", "IDD": "+599" },
    { "Name": "Cyprus", "Alpha-2": "CY", "IDD": "+357" },
    { "Name": "Czech Republic", "Alpha-2": "CZ", "IDD": "+420" },
    { "Name": "Democratic Republic of Timor-Leste", "Alpha-2": "TL", "IDD": "+670" },
    { "Name": "Denmark", "Alpha-2": "DK", "IDD": "+45" },
    { "Name": "Djibouti", "Alpha-2": "DJ", "IDD": "+253" },
    { "Name": "Dominica", "Alpha-2": "DM", "IDD": "+1-767" },
    { "Name": "Dominican Republic", "Alpha-2": "DO", "IDD": "+1-809 and 1-829" },
    { "Name": "Ecuador", "Alpha-2": "EC", "IDD": "+593" },
    { "Name": "Egypt", "Alpha-2": "EG", "IDD": "+20" },
    { "Name": "El Salvador", "Alpha-2": "SV", "IDD": "+503" },
    { "Name": "Equatorial Guinea", "Alpha-2": "GQ", "IDD": "+240" },
    { "Name": "Eritrea", "Alpha-2": "ER", "IDD": "+291" },
    { "Name": "Estonia", "Alpha-2": "EE", "IDD": "+372" },
    { "Name": "Ethiopia", "Alpha-2": "ET", "IDD": "+251" },
    { "Name": "Falkland Islands (Islas Malvinas)", "Alpha-2": "FK", "IDD": "+500" },
    { "Name": "Faroe Islands", "Alpha-2": "FO", "IDD": "+298" },
    { "Name": "Fiji Islands", "Alpha-2": "FJ", "IDD": "+679" },
    { "Name": "Finland", "Alpha-2": "FI", "IDD": "+358" },
    { "Name": "France", "Alpha-2": "FR", "IDD": "+33" },
    { "Name": "French Guiana", "Alpha-2": "GF", "IDD": "+594" },
    { "Name": "French Polynesia", "Alpha-2": "PF", "IDD": "+689" },
    { "Name": "French Southern and Antarctic Lands", "Alpha-2": "TF", "IDD": "+" },
    { "Name": "Gabon", "Alpha-2": "GA", "IDD": "+241" },
    { "Name": "Gambia, The", "Alpha-2": "GM", "IDD": "+220" },
    { "Name": "Georgia", "Alpha-2": "GE", "IDD": "+995" },
    { "Name": "Germany", "Alpha-2": "DE", "IDD": "+49" },
    { "Name": "Ghana", "Alpha-2": "GH", "IDD": "+233" },
    { "Name": "Gibraltar", "Alpha-2": "GI", "IDD": "+350" },
    { "Name": "Greece", "Alpha-2": "GR", "IDD": "+30" },
    { "Name": "Greenland", "Alpha-2": "GL", "IDD": "+299" },
    { "Name": "Grenada", "Alpha-2": "GD", "IDD": "+1-473" },
    { "Name": "Guadeloupe", "Alpha-2": "GP", "IDD": "+590" },
    { "Name": "Guam", "Alpha-2": "GU", "IDD": "+1-671" },
    { "Name": "Guatemala", "Alpha-2": "GT", "IDD": "+502" },
    { "Name": "Guernsey", "Alpha-2": "GG", "IDD": "+44-1481" },
    { "Name": "Guinea", "Alpha-2": "GN", "IDD": "+224" },
    { "Name": "Guinea-Bissau", "Alpha-2": "GW", "IDD": "+245" },
    { "Name": "Guyana", "Alpha-2": "GY", "IDD": "+592" },
    { "Name": "Haiti", "Alpha-2": "HT", "IDD": "+509" },
    { "Name": "Heard Island and McDonald Islands", "Alpha-2": "HM", "IDD": "+ " },
    { "Name": "Honduras", "Alpha-2": "HN", "IDD": "+504" },
    { "Name": "Hong Kong SAR", "Alpha-2": "HK", "IDD": "+852" },
    { "Name": "Hungary", "Alpha-2": "HU", "IDD": "+36" },
    { "Name": "Iceland", "Alpha-2": "IS", "IDD": "+354" },
    { "Name": "India", "Alpha-2": "IN", "IDD": "+91" },
    { "Name": "Indonesia", "Alpha-2": "ID", "IDD": "+62" },
    { "Name": "Iran", "Alpha-2": "IR", "IDD": "+98" },
    { "Name": "Iraq", "Alpha-2": "IQ", "IDD": "+964" },
    { "Name": "Ireland", "Alpha-2": "IE", "IDD": "+353" },
    { "Name": "Israel", "Alpha-2": "IL", "IDD": "+972" },
    { "Name": "Italy", "Alpha-2": "IT", "IDD": "+39" },
    { "Name": "Jamaica", "Alpha-2": "JM", "IDD": "+1-876" },
    { "Name": "Jan Mayen", "Alpha-2": "SJ", "IDD": "+47" },
    { "Name": "Japan", "Alpha-2": "JP", "IDD": "+81" },
    { "Name": "Jersey", "Alpha-2": "JE", "IDD": "+44-1534" },
    { "Name": "Jordan", "Alpha-2": "JO", "IDD": "+962" },
    { "Name": "Kazakhstan", "Alpha-2": "KZ", "IDD": "+7" },
    { "Name": "Kenya", "Alpha-2": "KE", "IDD": "+254" },
    { "Name": "Kiribati", "Alpha-2": "KI", "IDD": "+686" },
    { "Name": "Korea", "Alpha-2": "KR", "IDD": "+82" },
    { "Name": "Kosovo", "Alpha-2": "XK", "IDD": "+" },
    { "Name": "Kuwait", "Alpha-2": "KW", "IDD": "+965" },
    { "Name": "Kyrgyzstan", "Alpha-2": "KG", "IDD": "+996" },
    { "Name": "Laos", "Alpha-2": "LA", "IDD": "+856" },
    { "Name": "Latvia", "Alpha-2": "LV", "IDD": "+371" },
    { "Name": "Lebanon", "Alpha-2": "LB", "IDD": "+961" },
    { "Name": "Lesotho", "Alpha-2": "LS", "IDD": "+266" },
    { "Name": "Liberia", "Alpha-2": "LR", "IDD": "+231" },
    { "Name": "Libya", "Alpha-2": "LY", "IDD": "+218" },
    { "Name": "Liechtenstein", "Alpha-2": "LI", "IDD": "+423" },
    { "Name": "Lithuania", "Alpha-2": "LT", "IDD": "+370" },
    { "Name": "Luxembourg", "Alpha-2": "LU", "IDD": "+352" },
    { "Name": "Macao SAR", "Alpha-2": "MO", "IDD": "+853" },
    { "Name": "Macedonia, Former Yugoslav Republic of", "Alpha-2": "MK", "IDD": "+389" },
    { "Name": "Madagascar", "Alpha-2": "MG", "IDD": "+261" },
    { "Name": "Malawi", "Alpha-2": "MW", "IDD": "+265" },
    { "Name": "Malaysia", "Alpha-2": "MY", "IDD": "+60" },
    { "Name": "Maldives", "Alpha-2": "MV", "IDD": "+960" },
    { "Name": "Mali", "Alpha-2": "ML", "IDD": "+223" },
    { "Name": "Malta", "Alpha-2": "MT", "IDD": "+356" },
    { "Name": "Man, Isle of", "Alpha-2": "IM", "IDD": "+44-1624" },
    { "Name": "Marshall Islands", "Alpha-2": "MH", "IDD": "+692" },
    { "Name": "Martinique", "Alpha-2": "MQ", "IDD": "+596" },
    { "Name": "Mauritania", "Alpha-2": "MR", "IDD": "+222" },
    { "Name": "Mauritius", "Alpha-2": "MU", "IDD": "+230" },
    { "Name": "Mayotte", "Alpha-2": "YT", "IDD": "+262" },
    { "Name": "Mexico", "Alpha-2": "MX", "IDD": "+52" },
    { "Name": "Micronesia", "Alpha-2": "FM", "IDD": "+691" },
    { "Name": "Moldova", "Alpha-2": "MD", "IDD": "+373" },
    { "Name": "Monaco", "Alpha-2": "MC", "IDD": "+377" },
    { "Name": "Mongolia", "Alpha-2": "MN", "IDD": "+976" },
    { "Name": "Montenegro", "Alpha-2": "ME", "IDD": "+382" },
    { "Name": "Montserrat", "Alpha-2": "MS", "IDD": "+1-664" },
    { "Name": "Morocco", "Alpha-2": "MA", "IDD": "+212" },
    { "Name": "Mozambique", "Alpha-2": "MZ", "IDD": "+258" },
    { "Name": "Myanmar", "Alpha-2": "MM", "IDD": "+95" },
    { "Name": "Namibia", "Alpha-2": "NA", "IDD": "+264" },
    { "Name": "Nauru", "Alpha-2": "NR", "IDD": "+674" },
    { "Name": "Nepal", "Alpha-2": "NP", "IDD": "+977" },
    { "Name": "Netherlands", "Alpha-2": "NL", "IDD": "+31" },
    { "Name": "New Caledonia", "Alpha-2": "NC", "IDD": "+687" },
    { "Name": "New Zealand", "Alpha-2": "NZ", "IDD": "+64" },
    { "Name": "Nicaragua", "Alpha-2": "NI", "IDD": "+505" },
    { "Name": "Niger", "Alpha-2": "NE", "IDD": "+227" },
    { "Name": "Nigeria", "Alpha-2": "NG", "IDD": "+234" },
    { "Name": "Niue", "Alpha-2": "NU", "IDD": "+683" },
    { "Name": "Norfolk Island", "Alpha-2": "NF", "IDD": "+672" },
    { "Name": "North Korea", "Alpha-2": "KP", "IDD": "+850" },
    { "Name": "Northern Mariana Islands", "Alpha-2": "MP", "IDD": "+1-670" },
    { "Name": "Norway", "Alpha-2": "NO", "IDD": "+47" },
    { "Name": "Oman", "Alpha-2": "OM", "IDD": "+968" },
    { "Name": "Pakistan", "Alpha-2": "PK", "IDD": "+92" },
    { "Name": "Palau", "Alpha-2": "PW", "IDD": "+680" },
    { "Name": "Palestinian Authority", "Alpha-2": "PS", "IDD": "+970" },
    { "Name": "Panama", "Alpha-2": "PA", "IDD": "+507" },
    { "Name": "Papua New Guinea", "Alpha-2": "PG", "IDD": "+675" },
    { "Name": "Paraguay", "Alpha-2": "PY", "IDD": "+595" },
    { "Name": "Peru", "Alpha-2": "PE", "IDD": "+51" },
    { "Name": "Philippines", "Alpha-2": "PH", "IDD": "+63" },
    { "Name": "Pitcairn Islands", "Alpha-2": "PN", "IDD": "+870" },
    { "Name": "Poland", "Alpha-2": "PL", "IDD": "+48" },
    { "Name": "Portugal", "Alpha-2": "PT", "IDD": "+351" },
    { "Name": "Puerto Rico", "Alpha-2": "PR", "IDD": "+1-787 and 1-939" },
    { "Name": "Qatar", "Alpha-2": "QA", "IDD": "+974" },
    { "Name": "Reunion", "Alpha-2": "RE", "IDD": "+262" },
    { "Name": "Romania", "Alpha-2": "RO", "IDD": "+40" },
    { "Name": "Russia", "Alpha-2": "RU", "IDD": "+7" },
    { "Name": "Rwanda", "Alpha-2": "RW", "IDD": "+250" },
    { "Name": "Saint Barthélemy", "Alpha-2": "BL", "IDD": "+590" },
    { "Name": "Saint Helena, Ascension and Tristan da Cunha", "Alpha-2": "SH", "IDD": "+290" },
    { "Name": "Saint Kitts and Nevis", "Alpha-2": "KN", "IDD": "+1-869" },
    { "Name": "Saint Lucia", "Alpha-2": "LC", "IDD": "+1-758" },
    { "Name": "Saint Martin (French part)", "Alpha-2": "MF", "IDD": "+590" },
    { "Name": "Saint Pierre and Miquelon", "Alpha-2": "PM", "IDD": "+508" },
    { "Name": "Saint Vincent and the Grenadines", "Alpha-2": "VC", "IDD": "+1-784" },
    { "Name": "Samoa", "Alpha-2": "WS", "IDD": "+685" },
    { "Name": "San Marino", "Alpha-2": "SM", "IDD": "+378" },
    { "Name": "São Tomé and Príncipe", "Alpha-2": "ST", "IDD": "+239" },
    { "Name": "Saudi Arabia", "Alpha-2": "SA", "IDD": "+966" },
    { "Name": "Senegal", "Alpha-2": "SN", "IDD": "+221" },
    { "Name": "Serbia", "Alpha-2": "RS", "IDD": "+381" },
    { "Name": "Seychelles", "Alpha-2": "SC", "IDD": "+248" },
    { "Name": "Sierra Leone", "Alpha-2": "SL", "IDD": "+232" },
    { "Name": "Singapore", "Alpha-2": "SG", "IDD": "+65" },
    { "Name": "Sint Maarten (Dutch part)", "Alpha-2": "SX", "IDD": "+599" },
    { "Name": "Slovakia", "Alpha-2": "SK", "IDD": "+421" },
    { "Name": "Slovenia", "Alpha-2": "SI", "IDD": "+386" },
    { "Name": "Solomon Islands", "Alpha-2": "SB", "IDD": "+677" },
    { "Name": "Somalia", "Alpha-2": "SO", "IDD": "+252" },
    { "Name": "South Africa", "Alpha-2": "ZA", "IDD": "+27" },
    { "Name": "South Georgia and the South Sandwich Islands", "Alpha-2": "GS", "IDD": "+" },
    { "Name": "South Sudan", "Alpha-2": "SS", "IDD": "+211" },
    { "Name": "Spain", "Alpha-2": "ES", "IDD": "+34" },
    { "Name": "Sri Lanka", "Alpha-2": "LK", "IDD": "+94" },
    { "Name": "Sudan", "Alpha-2": "SD", "IDD": "+249" },
    { "Name": "Suriname", "Alpha-2": "SR", "IDD": "+597" },
    { "Name": "Svalbard", "Alpha-2": "SJ", "IDD": "+47" },
    { "Name": "Swaziland", "Alpha-2": "SZ", "IDD": "+268" },
    { "Name": "Sweden", "Alpha-2": "SE", "IDD": "+46" },
    { "Name": "Switzerland", "Alpha-2": "CH", "IDD": "+41" },
    { "Name": "Syria", "Alpha-2": "SY", "IDD": "+963" },
    { "Name": "Taiwan", "Alpha-2": "TW", "IDD": "+886" },
    { "Name": "Tajikistan", "Alpha-2": "TJ", "IDD": "+992" },
    { "Name": "Tanzania", "Alpha-2": "TZ", "IDD": "+255" },
    { "Name": "Thailand", "Alpha-2": "TH", "IDD": "+66" },
    { "Name": "Togo", "Alpha-2": "TG", "IDD": "+228" },
    { "Name": "Tokelau", "Alpha-2": "TK", "IDD": "+690" },
    { "Name": "Tonga", "Alpha-2": "TO", "IDD": "+676" },
    { "Name": "Trinidad and Tobago", "Alpha-2": "TT", "IDD": "+1-868" },
    { "Name": "Tunisia", "Alpha-2": "TN", "IDD": "+216" },
    { "Name": "Turkey", "Alpha-2": "TR", "IDD": "+90" },
    { "Name": "Turkmenistan", "Alpha-2": "TM", "IDD": "+993" },
    { "Name": "Turks and Caicos Islands", "Alpha-2": "TC", "IDD": "+1-649" },
    { "Name": "Tuvalu", "Alpha-2": "TV", "IDD": "+688" },
    { "Name": "U.S. Minor Outlying Islands", "Alpha-2": "UM", "IDD": "+1" },
    { "Name": "Uganda", "Alpha-2": "UG", "IDD": "+256" },
    { "Name": "Ukraine", "Alpha-2": "UA", "IDD": "+380" },
    { "Name": "United Arab Emirates", "Alpha-2": "AE", "IDD": "+971" },
    { "Name": "United Kingdom", "Alpha-2": "GB", "IDD": "+44" },
    { "Name": "United States", "Alpha-2": "US", "IDD": "+1" },
    { "Name": "Uruguay", "Alpha-2": "UY", "IDD": "+598" },
    { "Name": "Uzbekistan", "Alpha-2": "UZ", "IDD": "+998" },
    { "Name": "Vanuatu", "Alpha-2": "VU", "IDD": "+678" },
    { "Name": "Vatican City", "Alpha-2": "VA", "IDD": "+379" },
    { "Name": "Vietnam", "Alpha-2": "VN", "IDD": "+84" },
    { "Name": "Virgin Islands, U.S.", "Alpha-2": "VI", "IDD": "+1-340" },
    { "Name": "Virgin Islands, British", "Alpha-2": "VG", "IDD": "+1-284" },
    { "Name": "Wallis and Futuna", "Alpha-2": "WF", "IDD": "+681" },
    { "Name": "Yemen", "Alpha-2": "YE", "IDD": "+967" },
    { "Name": "Zambia", "Alpha-2": "ZM", "IDD": "+260" },
    { "Name": "Zimbabwe", "Alpha-2": "ZW", "IDD": "+263" }
]